query ProjectBySlug($slug: String!) {
  projectBySlug(slug: $slug) {
    id
    title
    slug
    completion_date
    duration
    excerpt
    description
    area_of_improvement
    src_picture
    src_video
    team_members {
      name
      linkedin
    }
    technologies {
      name
      src_icon
    }
    created_at
    updated_at
  }
}
