query Projects($technologyIds: [Int!]) {
    projects(technologyIds: $technologyIds) {
        id
        title
        slug
        duration
        completion_date
        excerpt
        prof_env
        company_name
        src_picture
        team_members {
            id
            name
            src_icon
            linkedin
        }
        technologies {
            id
            name
            src_icon
        }
    }
}
