query Projects($technologyIds: [Int!]) {
  projects(technologyIds: $technologyIds) {
    id
    title
    slug
    completion_date
    excerpt
    prof_env
    company_name
    src_picture
    team_members {
      id
      name
      linkedin
    }
    technologies {
      id
      name
      src_icon
    }
  }
}
