services:
  db:
    image: postgres:15
    # a supprimer en dessous
    #ports:
    #  - 5432:5432
    # a supprimer au dessus
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/db.ts:/app/src/db.ts
    env_file:
      # - ./global.env
      - ./backend/.env
      # - ./secret.env
    environment:
      - DB_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
