services:
  db:
    image: postgres:15
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-postgres}
      PGUSER: ${DB_USER-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - prodDB:/var/lib/postgresql/data

  backend:
    environment:
      DB_HOST: db
      DB_PASS: ${DB_PASS-postgres}
      DB_USER: ${DB_USER-postgres}
      SECRET_KEY: ${SECRET_KEY:-changeme}
      NODE_ENV: ${NODE_ENV:-production}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-changeme}
      SITE_URL: ${SITE_URL:-production}
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    image: caudrel/portfolio-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    environment:
      SECRET_KEY: ${SECRET_KEY:-changeme}
    stop_grace_period: 0s
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    image: caudrel/portfolio-client
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q --spider http://localhost:3000 || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s

  gateway:
    # depends_on:
    #   backend:
    #     condition: service_healthy
    stop_grace_period: 0s
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile.production
    ports:
      - ${GATEWAY_PORT-80}:80

volumes:
  prodDB:
