services:
  db:
    image: postgres:15
    # a supprimer en dessous
    #ports:
    #  - 5432:5432
    # a supprimer au dessus
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/db.ts:/app/src/db.ts
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultPassword}
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - ./backend/.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultPassword}
    command: redis-server --requirepass "$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
