FROM node:20.9.0-alpine3.17

WORKDIR /app

# Installer curl pour les healthchecks
RUN apk add --no-cache curl

COPY package*.json ./

RUN npm ci

COPY ./tsconfig.json ./tsconfig.json

COPY ./src ./src

RUN npm run build

CMD ["npm", "run", "start:prod"]