name: Compile and push client and server to staging

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build-and-push-server:
    uses: Caudrel/Portfolio/.github/workflows/build-backend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: caudrel/portfolio-server-staging

  build-and-push-client:
    uses: Caudrel/Portfolio/.github/workflows/build-frontend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: caudrel/portfolio-client-staging

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.caudrel.com/hooks/update-staging
